wallpaper{
               monitor = eDP-1
               path = /home/leo/Bilder/hintergrund.png
               fit_mode = center
}
wallpaper{
               monitor = DP-3
               path = /home/leo/Bilder/hintergrund_bildschirm2.jpg
               fit_mode = center
}